# ワークフロー名
name: test
on:
  push:
    branches:
      - feature/cron
  schedule:
    - cron: '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - run: |
          python $GITHUB_WORKSPACE/main.py
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
